import React from 'react';
import clsx from 'clsx';
import {
  Star,
  Trophy,
  Crown,
  Medal,
  Award,
  BadgeCheck,
  Shield,
  ShieldCheck,
  Sparkles,
  Flame,
  Zap,
  Target,
  TrendingUp,
  TrendingDown,
  Minus,
  ArrowUpRight,
  ArrowDownRight,
  CheckCircle2,
  AlertTriangle,
  XCircle,
  Info,
  Clock,
  Calendar,
  Bell,
  BellRing,
  Search,
  Filter,
  SortAsc,
  BarChart3,
  PieChart,
  Activity,
  Users,
  UserCheck,
  Building2,
  Globe,
  MapPin,
  Phone,
  Mail,
  Send,
  MessageSquare,
  FileText,
  Download,
  Upload,
  Settings,
  SlidersHorizontal,
  Layout,
  Grid3X3,
  List,
  Eye,
  EyeOff,
  Lock,
  Unlock,
  Heart,
  Bookmark,
  Share2,
  Link2,
  ExternalLink,
  Copy,
  RefreshCw,
  RotateCcw,
  ChevronRight,
  ChevronLeft,
  ChevronDown,
  ChevronUp,
  Plus,
  Minus as MinusIcon,
  X,
  Check,
  Edit3,
  Trash2,
  MoreHorizontal,
  MoreVertical,
  Terminal,
  Cpu,
  Bot,
  Layers,
  Database,
  Wifi,
  WifiOff,
  Radio,
  Satellite,
  Compass,
  Navigation,
  Anchor,
} from 'lucide-react';

type IconName = keyof typeof iconRegistry;

const iconRegistry = {
  star: Star,
  trophy: Trophy,
  crown: Crown,
  medal: Medal,
  award: Award,
  badgeCheck: BadgeCheck,
  shield: Shield,
  shieldCheck: ShieldCheck,
  sparkles: Sparkles,
  flame: Flame,
  zap: Zap,
  target: Target,
  trendingUp: TrendingUp,
  trendingDown: TrendingDown,
  minus: Minus,
  arrowUpRight: ArrowUpRight,
  arrowDownRight: ArrowDownRight,
  checkCircle: CheckCircle2,
  alertTriangle: AlertTriangle,
  xCircle: XCircle,
  info: Info,
  clock: Clock,
  calendar: Calendar,
  bell: Bell,
  bellRing: BellRing,
  search: Search,
  filter: Filter,
  sortAsc: SortAsc,
  barChart: BarChart3,
  pieChart: PieChart,
  activity: Activity,
  users: Users,
  userCheck: UserCheck,
  building: Building2,
  globe: Globe,
  mapPin: MapPin,
  phone: Phone,
  mail: Mail,
  send: Send,
  messageSquare: MessageSquare,
  fileText: FileText,
  download: Download,
  upload: Upload,
  settings: Settings,
  sliders: SlidersHorizontal,
  layout: Layout,
  grid: Grid3X3,
  list: List,
  eye: Eye,
  eyeOff: EyeOff,
  lock: Lock,
  unlock: Unlock,
  heart: Heart,
  bookmark: Bookmark,
  share: Share2,
  link: Link2,
  externalLink: ExternalLink,
  copy: Copy,
  refresh: RefreshCw,
  rotateCcw: RotateCcw,
  chevronRight: ChevronRight,
  chevronLeft: ChevronLeft,
  chevronDown: ChevronDown,
  chevronUp: ChevronUp,
  plus: Plus,
  minusIcon: MinusIcon,
  x: X,
  check: Check,
  edit: Edit3,
  trash: Trash2,
  moreHorizontal: MoreHorizontal,
  moreVertical: MoreVertical,
  terminal: Terminal,
  cpu: Cpu,
  bot: Bot,
  layers: Layers,
  database: Database,
  wifi: Wifi,
  wifiOff: WifiOff,
  radio: Radio,
  satellite: Satellite,
  compass: Compass,
  navigation: Navigation,
  anchor: Anchor,
};

interface HeroIconProps {
  name: IconName;
  size?: 'xs' | 'sm' | 'md' | 'lg' | 'xl';
  className?: string;
  color?: string;
}

const sizeMap = {
  xs: 'w-3 h-3',
  sm: 'w-4 h-4',
  md: 'w-5 h-5',
  lg: 'w-6 h-6',
  xl: 'w-8 h-8',
};

export const HeroIcon: React.FC<HeroIconProps> = ({
  name,
  size = 'md',
  className,
  color,
}) => {
  const IconComponent = iconRegistry[name];
  if (!IconComponent) return null;

  return (
    <IconComponent
      className={clsx(sizeMap[size], color || 'text-current', className)}
    />
  );
};

export { iconRegistry };
export type { IconName };
